export const monitoringSummaryData = {
  totals: {
    openIssues: 18,
    criticalIssues: 4,
    eventsLast24Hours: 73,
    affectedUsers: 21,
  },

  timeline: {
    labels: [
      "20 jul.",
      "21 jul.",
      "22 jul.",
      "23 jul.",
      "24 jul.",
      "25 jul.",
      "26 jul.",
    ],

    datasets: [
      {
        label: "Aplicación móvil",
        data: [12, 18, 9, 22, 16, 28, 21],
        borderColor: "#6f9eed",
        backgroundColor: "rgba(111, 158, 237, 0.12)",
        pointBackgroundColor: "#6f9eed",
        tension: 0.35,
        fill: false,
      },
      {
        label: "Panel web",
        data: [5, 7, 4, 11, 8, 13, 9],
        borderColor: "#ff9955",
        backgroundColor: "rgba(255, 153, 85, 0.12)",
        pointBackgroundColor: "#ff9955",
        tension: 0.35,
        fill: false,
      },
      {
        label: "Backend",
        data: [3, 4, 2, 8, 5, 11, 6],
        borderColor: "#50c878",
        backgroundColor: "rgba(80, 200, 120, 0.12)",
        pointBackgroundColor: "#50c878",
        tension: 0.35,
        fill: false,
      },
    ],
  },

  projects: [
    {
      id: "mobile",
      name: "Aplicación móvil",
      technology: "React Native / Expo",
      openIssues: 9,
      criticalIssues: 2,
      events: 116,
      status: "warning",
    },
    {
      id: "web",
      name: "Panel web",
      technology: "React / Vite",
      openIssues: 5,
      criticalIssues: 0,
      events: 48,
      status: "operational",
    },
    {
      id: "backend",
      name: "Backend",
      technology: "Node.js / Firebase",
      openIssues: 4,
      criticalIssues: 2,
      events: 27,
      status: "critical",
    },
  ],

  topIssues: [
    {
      id: "issue-1",
      code: "LSEARCH-MOBILE-12",
      title: "No fue posible obtener la ubicación del dispositivo",
      project: "Aplicación móvil",
      module: "Ubicación",
      category: "location",
      level: "error",
      events: 43,
      users: 11,
      lastSeen: "Hace 8 minutos",
    },
    {
      id: "issue-2",
      code: "LSEARCH-BACKEND-7",
      title: "Error 500 al registrar una propuesta de lugar",
      project: "Backend",
      module: "Propuestas",
      category: "server",
      level: "fatal",
      events: 19,
      users: 4,
      lastSeen: "Hace 21 minutos",
    },
    {
      id: "issue-3",
      code: "LSEARCH-WEB-5",
      title: "Unhandled Promise Rejection al cargar reportes",
      project: "Panel web",
      module: "Reportes",
      category: "javascript",
      level: "error",
      events: 14,
      users: 7,
      lastSeen: "Hace 46 minutos",
    },
    {
      id: "issue-4",
      code: "LSEARCH-MOBILE-9",
      title: "Fallo durante la subida de fotografías",
      project: "Aplicación móvil",
      module: "Fotografías",
      category: "storage",
      level: "warning",
      events: 12,
      users: 8,
      lastSeen: "Hace 1 hora",
    },
    {
      id: "issue-5",
      code: "LSEARCH-BACKEND-3",
      title: "Timeout al consultar Google Places",
      project: "Backend",
      module: "Google Places",
      category: "network",
      level: "error",
      events: 8,
      users: 3,
      lastSeen: "Hace 2 horas",
    },
  ],

  categories: [
    {
      id: "network",
      label: "Red y servicios",
      value: 38,
      percentage: 84,
    },
    {
      id: "javascript",
      label: "Código JavaScript",
      value: 26,
      percentage: 68,
    },
    {
      id: "authentication",
      label: "Autenticación",
      value: 17,
      percentage: 45,
    },
    {
      id: "location",
      label: "Ubicación y mapa",
      value: 14,
      percentage: 37,
    },
    {
      id: "validation",
      label: "Datos y validaciones",
      value: 9,
      percentage: 24,
    },
    {
      id: "performance",
      label: "Rendimiento",
      value: 5,
      percentage: 13,
    },
  ],

  operationalAlerts: [
    {
      id: "alert-1",
      title: "Fallos de ubicación repetidos",
      description:
        "Se registraron múltiples errores al obtener coordenadas durante las últimas 24 horas.",
      project: "Aplicación móvil",
      severity: "critical",
      count: 43,
    },
    {
      id: "alert-2",
      title: "Resultados vacíos elevados",
      description:
        "Varias búsquedas finalizaron sin lugares disponibles para los filtros utilizados.",
      project: "Aplicación móvil",
      severity: "warning",
      count: 31,
    },
    {
      id: "alert-3",
      title: "Subidas de fotografías incompletas",
      description:
        "Algunas propuestas no lograron completar la carga de todos sus archivos.",
      project: "Aplicación móvil",
      severity: "warning",
      count: 12,
    },
    {
      id: "alert-4",
      title: "Timeouts de Google Places",
      description:
        "La consulta externa superó el tiempo máximo de respuesta permitido.",
      project: "Backend",
      severity: "warning",
      count: 8,
    },
  ],
};