const usersData = [
  {
    id: "1",
    name: "Dante Orozco",
    email: "dante@email.com",
    photoURL: null,
    registeredAt: "2026-06-24T18:30:00.000Z",
    profile: "Culinario",
    contributionsCount: 12,
    reportsCount: 1,
    status: "active",
  },
  {
    id: "2",
    name: "Usuario Aventurero",
    email: "aventurero@email.com",
    photoURL: null,
    registeredAt: "2026-06-20T13:10:00.000Z",
    profile: "Aventurero",
    contributionsCount: 8,
    reportsCount: 2,
    status: "under_observation",
  },
  {
    id: "3",
    name: "Usuario Cultural",
    email: "cultural@email.com",
    photoURL: null,
    registeredAt: "2026-06-18T09:45:00.000Z",
    profile: "Cultural",
    contributionsCount: 4,
    reportsCount: 0,
    status: "warned",
  },
  {
    id: "4",
    name: "Usuario Natural",
    email: "natural@email.com",
    photoURL: null,
    registeredAt: "2026-06-15T21:15:00.000Z",
    profile: "Naturaleza",
    contributionsCount: 18,
    reportsCount: 4,
    status: "limited",
  },
];

export default usersData;